### ISSUE TITLE
condition in stop(github_error(request)): Bad credentials (401)

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [jokergoo/GetoptLong#1]
Hi jokergoo, when I try

devtools::install_github("jokergoo/GetoptLong")

on my R shell I get: 

condition in stop(github_error(request)): Bad credentials (401)
- Traceback:
1. devtools::install_github("jokergoo/GetoptLong")
2. install_remotes(remotes, quiet = quiet, ...)
3. vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
4. FUN(X[[i]], ...)
5. remote_download(remote, quiet = quiet)
6. remote_download.github_remote(remote, quiet = quiet)
7. download_github(dest, src, auth)

Have you seen this error message before?
thanks
Alex

**Comment by jokergoo** [comment]
I think this is a problem when you download something from github. Can you try similar command with other packages or can you do it in the native R terminal?

**Comment by alexDeCastroAtGit** [comment]
fixed it jokergoo. i was downloading the package from the jupyter terminal. It worked fine from the R shell.

(I was using ROR 3.3)

thanks a lot

________________________________
