### ISSUE TITLE
Subcommand is possibly supported in the future?

### ISSUE THREAD

**Issue by ShixiangWang** [jokergoo/GetoptLong#10]
Hi @jokergoo,

Thanks for developing this nice tool, I found it easy and elegant. I am writing some related scripts based on it. I am wondering subcommand is possibly implemented in the future?

Best,

Shixiang

**Comment by jokergoo** [comment]
I don't know how easy it is to support subcommand, but I will keep it in mind.

**Comment by ShixiangWang** [comment]
Thanks :)

**Comment by jokergoo** [comment]
Trying to implement subcommands. In the following, `main.R` is the main script and it contains two sub scripts `foo1.R` and `foo2.R` with subcommands `foo1` and `foo2`:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/449218/161126884-bd78eec9-6af3-4f71-9781-840f61667ca4.png">

**Comment by jokergoo** [comment]
code in `main.R`:

```r

library(GetoptLong)

subCommands(
  "----", "----", "This is section1",
  "sub1", "sub1.R", 
          "This is the description of sub command 1, which will be a long long long text.",
  "----", "----", "This is section2",
  "sub2", "sub2.R",
          "This is the description of sub command 2, which will be a long long long text."
)
```

Code in `sub1.R`:

```r
library(GetoptLong)

GetoptLong("foo1=i", "foo1")

qqcat("foo1 = @{foo1}\n")
```

Code in `sub2.R`:

```r
library(GetoptLong)

GetoptLong("foo2=i", "foo2")

qqcat("foo2 = @{foo2}\n")
```

**Comment by ShixiangWang** [comment]
@jokergoo Thanks :).
