### ISSUE TITLE
how to use version opt and subcommands? 

### ISSUE THREAD

**Issue by felixlee0608** [jokergoo/GetoptLong#15]

**Comment by jokergoo** [comment]
The newest version has been updated to CRAN yet. You can find the documentation of using subcommands here: http://jokergoo.github.io/GetoptLong/articles/sub_commands.html

For define the version, simply set a variable `VERSION` before using `GetoptLong()`. http://jokergoo.github.io/GetoptLong/articles/GetoptLong.html#version-option
