### ISSUE TITLE
Failed to install this R package in R-3.5.1

### ISSUE THREAD

**Issue by Wangxin555** [jokergoo/GetoptLong#6]
Hi,

The package we are developing is dependent on this GetoptLong package. 
But we failed to install this package in R-3.5.1 when we were testing our package, and more than one device got this error.
Can you have a look and find the possible reason?

**The Chinese characters in the code below mean 'There is no package called GetoptLong'**
```
> install.packages("GetoptLong")
Warning message:
package ‘GetoptLong’ is not available (for R version 3.5.1) 
> library("GetoptLong")
Error in library("GetoptLong") : 不存在叫‘GetoptLong’这个名字的程辑包
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                               LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_3.5.1      tools_3.5.1         remotes_2.1.1
```
Thank you so much!

**Comment by jokergoo** [comment]
The newest version of GetoptLong has a dependency of R>=3.6.0, so maybe you should upgrade your R...

Or you can install the older versions by:

```r
install.packages("https://cran.r-project.org/src/contrib/Archive/GetoptLong/GetoptLong_0.1.8.tar.gz", repo = NULL)
```

If it doesn't work, change the version to one lower: https://cran.r-project.org/src/contrib/Archive/GetoptLong/

**Comment by Wangxin555** [comment]
I see.
But when I tried to install `ComplexHeatmap` package in R-3.5.1, it said that `dependency ‘GetoptLong’ is not available`, and there was no information about which version of GetoptLong I need to install.

```
> BiocManager::install("ComplexHeatmap")
Bioconductor version 3.8 (BiocManager 1.30.10), R 3.5.1 (2018-07-02)
Installing package(s) 'ComplexHeatmap'
Warning: dependency ‘GetoptLong’ is not available
also installing the dependencies ‘shape’, ‘circlize’, ‘colorspace’, ‘RColorBrewer’, ‘GlobalOptions’

```

**The Chinese characters in the code below mean 'There is no package called GetoptLong'**

```
> library(ComplexHeatmap)
Error: package or namespace load failed for ‘ComplexHeatmap’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 不存在叫‘GetoptLong’这个名字的程辑包
```


Thanks!

**Comment by jokergoo** [comment]
Yes, it basically means there is no such package under your R version.
